### ISSUE TITLE
Concourse image cache import slower than docker pull.

### ISSUE THREAD

**Issue by jimsynz** [product-os/scripts#105]
When debugging some slow builds on Jellyfish we noticed that the test spends ~3 minutes pulling images from the concourse image cache and importing them. Unfortunately due to the way that we're using `docker load` we are missing out on concurrency and layer caching that we'd get if we were just using `docker pull` directly.  Perhaps we should remove this extra complexity and just use pull?

**Example:** https://ci.balena-dev.com/builds/8662#L5eb78206:1

**Comment by joshbwlng** [comment]
@jimsynz Sounds like a great idea that we should at least try out and get some numbers to compare. I'm assuming the change would be here: https://github.com/balena-io/scripts/blob/master/docker/image-cache.sh#L16

@nazrhom What do you think?

**Comment by nazrhom** [comment]
@jimsynz @joshbwlng. We have 3 docker tasks: build, test and store. We use `docker save` in the build task and try to docker load  `docker load` the images back in the test and store one.
It doesn't make too much sense to `docker pull` anything between the build and store task, as there is nothing to pull (we could in alternative consolidate build and store into a single task). We could run the build, store the images if successful and then pull them from the registry for the compose tests, I wouldn't have guessed this is faster, but Im up to give it a try
